services:
  sentiment:
    image: datascientest/fastapi:1.0.0
    container_name: sentiment_api
    networks:
      - sentimentnw
    ports:
      - "8000:8000"
  status:
    depends_on:
      sentiment:
        condition: service_started
    image: status
    #pull_policy: build
    #build: ./status
    container_name: status_test
    networks:
      - sentimentnw
    volumes:
      - .:/home/logs
    environment:
      LOG: ${LOG}
  authentification:
    depends_on:
      status:
        condition: service_completed_successfully
    #build: ./authentification
    image: authentification:latest
    #pull_policy: build
    container_name: authentification_test
    networks:
      - sentimentnw
    volumes:
      - .:/home/logs
    environment:
      LOG: ${LOG}
  authorization:
    depends_on:
      authentification:
        condition: service_completed_successfully
    #build: ./authorization
    image: authorization:latest
    #pull_policy: build
    container_name: authorization_test
    networks:
      - sentimentnw
    volumes:
      - .:/home/logs
    environment:
      LOG: ${LOG}
  content:
    depends_on:
      authorization:
        condition: service_completed_successfully
    #build: ./content
    image: content:latest
    #pull_policy: build
    container_name: content_test
    networks:
      - sentimentnw
    volumes:
      - .:/home/logs
    environment:
      LOG: ${LOG}
networks:
  sentimentnw:


